### ISSUE TITLE
Suggestion : Highlight Focused Card with Color Briefly

### ISSUE THREAD

**Issue by rkrc-hp** [ddalexb/obsidian-simple-canvasearch#1]
Humble Suggestion : Highlighting the Card brought to focus at the end of the search-flow, with a colored border, background or shadow for 2-5 seconds would be really helpful. Please think about it, thanks.

Awesome plugin btw 🔥

**Comment by 19msb** [comment]
This has been resolved in the release 1.1.1 June 18 2024. Selected note is outlined. If multiple are selected, they will all be outlined.
